version: '3'

networks:
  webapp:

services:
  web:
    image: nginx:1.25-alpine3.17
    ports:
      - "${PORT_WEB}:80"
    volumes:
      - ./www:/www:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
    networks:
      - webapp
  php:
    image: php:8.2-fpm-alpine3.17 
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./www:/www:rw
    networks:
      - webapp
